# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mrcloudland.github.io
tagline:          
url:              http://mrcloudland.github.io
paginate:         3
baseurl:          /
author:
  name:           
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           
